//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrowGuard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThrowGuard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error occurred..
        /// </summary>
        internal static string Err_AppException {
            get {
                return ResourceManager.GetString("Err_AppException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is not valid..
        /// </summary>
        internal static string Err_BadArg {
            get {
                return ResourceManager.GetString("Err_BadArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value represents a whitespace character..
        /// </summary>
        internal static string Err_Char_Whitespace {
            get {
                return ResourceManager.GetString("Err_Char_Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains {0} element(s)..
        /// </summary>
        internal static string Err_Collection_Count_Is {
            get {
                return ResourceManager.GetString("Err_Collection_Count_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains {0} element(s); expected exactly {1}..
        /// </summary>
        internal static string Err_Collection_Count_IsNot {
            get {
                return ResourceManager.GetString("Err_Collection_Count_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains {0} element(s); expected less than {1}..
        /// </summary>
        internal static string Err_Collection_Count_LessThan {
            get {
                return ResourceManager.GetString("Err_Collection_Count_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains {0} element(s); expected less than or equal to {1}..
        /// </summary>
        internal static string Err_Collection_Count_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Err_Collection_Count_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains {0} element(s); expected more than {1}..
        /// </summary>
        internal static string Err_Collection_Count_MoreThan {
            get {
                return ResourceManager.GetString("Err_Collection_Count_MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains {0} element(s); expected more than or equal to {1}..
        /// </summary>
        internal static string Err_Collection_Count_MoreThanOrEqualTo {
            get {
                return ResourceManager.GetString("Err_Collection_Count_MoreThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains no elements; it is empty..
        /// </summary>
        internal static string Err_Collection_IsEmpty {
            get {
                return ResourceManager.GetString("Err_Collection_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more elements in the collection match the specified predicate expression..
        /// </summary>
        internal static string Err_Collection_Item_Any {
            get {
                return ResourceManager.GetString("Err_Collection_Item_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more elements in the collection do not match the specified predicate expression..
        /// </summary>
        internal static string Err_Collection_Item_AnyNot {
            get {
                return ResourceManager.GetString("Err_Collection_Item_AnyNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more elements in the collection are a null or empty string..
        /// </summary>
        internal static string Err_Collection_Item_NullOrEmpty {
            get {
                return ResourceManager.GetString("Err_Collection_Item_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more elements in the collection are a null string or contain only whitespace..
        /// </summary>
        internal static string Err_Collection_Item_NullOrWhitespace {
            get {
                return ResourceManager.GetString("Err_Collection_Item_NullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist..
        /// </summary>
        internal static string Err_Directory_NotFound {
            get {
                return ResourceManager.GetString("Err_Directory_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist: &apos;{0}&apos;..
        /// </summary>
        internal static string Err_Directory_NotFound_Path {
            get {
                return ResourceManager.GetString("Err_Directory_NotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a member of the enumerated type..
        /// </summary>
        internal static string Err_Enum_NotMember {
            get {
                return ResourceManager.GetString("Err_Enum_NotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a member of enum type {1}..
        /// </summary>
        internal static string Err_Enum_NotMember_Fmt {
            get {
                return ResourceManager.GetString("Err_Enum_NotMember_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error occurred..
        /// </summary>
        internal static string Err_Exception {
            get {
                return ResourceManager.GetString("Err_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file does not exist..
        /// </summary>
        internal static string Err_File_NotFound {
            get {
                return ResourceManager.GetString("Err_File_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file does not exist: &apos;{0}&apos;..
        /// </summary>
        internal static string Err_File_NotFound_Path {
            get {
                return ResourceManager.GetString("Err_File_NotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is an empty GUID (Guid.Empty)..
        /// </summary>
        internal static string Err_GuidEmpty {
            get {
                return ResourceManager.GetString("Err_GuidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified cast is not valid..
        /// </summary>
        internal static string Err_InvalidCast {
            get {
                return ResourceManager.GetString("Err_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not valid..
        /// </summary>
        internal static string Err_InvalidOp {
            get {
                return ResourceManager.GetString("Err_InvalidOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented..
        /// </summary>
        internal static string Err_NotImplemented {
            get {
                return ResourceManager.GetString("Err_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument contains a null reference..
        /// </summary>
        internal static string Err_NullArg {
            get {
                return ResourceManager.GetString("Err_NullArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is betwwen {1} and {2}, inclusive..
        /// </summary>
        internal static string Err_Num_Between {
            get {
                return ResourceManager.GetString("Err_Num_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is equal to the specified other value ({0})..
        /// </summary>
        internal static string Err_Num_EqualTo {
            get {
                return ResourceManager.GetString("Err_Num_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is greater than {1}..
        /// </summary>
        internal static string Err_Num_GreaterThan {
            get {
                return ResourceManager.GetString("Err_Num_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is greater than or equal to {1}..
        /// </summary>
        internal static string Err_Num_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Err_Num_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is less than {1}..
        /// </summary>
        internal static string Err_Num_LessThan {
            get {
                return ResourceManager.GetString("Err_Num_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is less than or equal to {1}..
        /// </summary>
        internal static string Err_Num_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Err_Num_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is a negative number..
        /// </summary>
        internal static string Err_Num_Negative {
            get {
                return ResourceManager.GetString("Err_Num_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not betwwen {1} and {2}, inclusive..
        /// </summary>
        internal static string Err_Num_NotBetween {
            get {
                return ResourceManager.GetString("Err_Num_NotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not equal to the specified other value ({1})..
        /// </summary>
        internal static string Err_Num_NotEqualTo {
            get {
                return ResourceManager.GetString("Err_Num_NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not a negative number..
        /// </summary>
        internal static string Err_Num_NotNegative {
            get {
                return ResourceManager.GetString("Err_Num_NotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not a positive number..
        /// </summary>
        internal static string Err_Num_NotPositive {
            get {
                return ResourceManager.GetString("Err_Num_NotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not zero..
        /// </summary>
        internal static string Err_Num_NotZero {
            get {
                return ResourceManager.GetString("Err_Num_NotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is a positive number..
        /// </summary>
        internal static string Err_Num_Positive {
            get {
                return ResourceManager.GetString("Err_Num_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is zero..
        /// </summary>
        internal static string Err_Num_Zero {
            get {
                return ResourceManager.GetString("Err_Num_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is out of range..
        /// </summary>
        internal static string Err_OutOfRange {
            get {
                return ResourceManager.GetString("Err_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value ({0}) is out of range; value must be between {1} and {2}..
        /// </summary>
        internal static string Err_OutOfRange_Fmt {
            get {
                return ResourceManager.GetString("Err_OutOfRange_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string value is empty..
        /// </summary>
        internal static string Err_Str_Empty {
            get {
                return ResourceManager.GetString("Err_Str_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string value contains a null reference or is an empty string..
        /// </summary>
        internal static string Err_Str_NullOrEmpty {
            get {
                return ResourceManager.GetString("Err_Str_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string value contains a null reference, is an empty string, or contains only whitespace..
        /// </summary>
        internal static string Err_Str_NullOrWhitespace {
            get {
                return ResourceManager.GetString("Err_Str_NullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string value is empty or contains only whitespace..
        /// </summary>
        internal static string Err_Str_Whitespace {
            get {
                return ResourceManager.GetString("Err_Str_Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTimeKind is {0}..
        /// </summary>
        internal static string Err_Uri_DateTimeKindIs {
            get {
                return ResourceManager.GetString("Err_Uri_DateTimeKindIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTimeKind is not {0}..
        /// </summary>
        internal static string Err_Uri_DateTimeKindIsNot {
            get {
                return ResourceManager.GetString("Err_Uri_DateTimeKindIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri host is &apos;{0}&apos;..
        /// </summary>
        internal static string Err_Uri_HostIs {
            get {
                return ResourceManager.GetString("Err_Uri_HostIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri host is not &apos;{0}&apos;..
        /// </summary>
        internal static string Err_Uri_HostIsNot {
            get {
                return ResourceManager.GetString("Err_Uri_HostIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri host-name-type is {0}..
        /// </summary>
        internal static string Err_Uri_HostNameTypeIs {
            get {
                return ResourceManager.GetString("Err_Uri_HostNameTypeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri host-name-type is not {0}..
        /// </summary>
        internal static string Err_Uri_HostNameTypeIsNot {
            get {
                return ResourceManager.GetString("Err_Uri_HostNameTypeIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri instance is Absolute..
        /// </summary>
        internal static string Err_Uri_IsAbsolute {
            get {
                return ResourceManager.GetString("Err_Uri_IsAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri &apos;{0}&apos; is a base of &apos;{1}&apos;..
        /// </summary>
        internal static string Err_Uri_IsBaseOf {
            get {
                return ResourceManager.GetString("Err_Uri_IsBaseOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri is a File uri..
        /// </summary>
        internal static string Err_Uri_IsFile {
            get {
                return ResourceManager.GetString("Err_Uri_IsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri references the local host..
        /// </summary>
        internal static string Err_Uri_IsLoopback {
            get {
                return ResourceManager.GetString("Err_Uri_IsLoopback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri &apos;{0}&apos; is not a base of &apos;{1}&apos;..
        /// </summary>
        internal static string Err_Uri_IsNotBaseOf {
            get {
                return ResourceManager.GetString("Err_Uri_IsNotBaseOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri is not a File uri..
        /// </summary>
        internal static string Err_Uri_IsNotFile {
            get {
                return ResourceManager.GetString("Err_Uri_IsNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri does not reference the local host..
        /// </summary>
        internal static string Err_Uri_IsNotLoopback {
            get {
                return ResourceManager.GetString("Err_Uri_IsNotLoopback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri is not a Unc uri..
        /// </summary>
        internal static string Err_Uri_IsNotUnc {
            get {
                return ResourceManager.GetString("Err_Uri_IsNotUnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri instance is Relative..
        /// </summary>
        internal static string Err_Uri_IsRelative {
            get {
                return ResourceManager.GetString("Err_Uri_IsRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri is a Unc uri..
        /// </summary>
        internal static string Err_Uri_IsUnc {
            get {
                return ResourceManager.GetString("Err_Uri_IsUnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri port is {0}..
        /// </summary>
        internal static string Err_Uri_PortIs {
            get {
                return ResourceManager.GetString("Err_Uri_PortIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri uses the default port for the scheme..
        /// </summary>
        internal static string Err_Uri_PortIsDefault {
            get {
                return ResourceManager.GetString("Err_Uri_PortIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri port is not {0}..
        /// </summary>
        internal static string Err_Uri_PortIsNot {
            get {
                return ResourceManager.GetString("Err_Uri_PortIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri does not use the default port for the scheme..
        /// </summary>
        internal static string Err_Uri_PortIsNotDefault {
            get {
                return ResourceManager.GetString("Err_Uri_PortIsNotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri scheme is {0}..
        /// </summary>
        internal static string Err_Uri_SchemeIs {
            get {
                return ResourceManager.GetString("Err_Uri_SchemeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri scheme is not {0}..
        /// </summary>
        internal static string Err_Uri_SchemeIsNot {
            get {
                return ResourceManager.GetString("Err_Uri_SchemeIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A validation error occurred..
        /// </summary>
        internal static string Err_ValidationError {
            get {
                return ResourceManager.GetString("Err_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No argument name given..
        /// </summary>
        internal static string Msg_NoArgName {
            get {
                return ResourceManager.GetString("Msg_NoArgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predicate condition is true..
        /// </summary>
        internal static string Msg_PredicateIsTrue {
            get {
                return ResourceManager.GetString("Msg_PredicateIsTrue", resourceCulture);
            }
        }
    }
}
