name: Build-And-Test

on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest #windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x.x
    - name: Restore dependencies
      run: dotnet restore ./ThrowGuard.sln
    - name: Build
      run: dotnet build ./ThrowGuard.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./ThrowGuard.sln -c Release
      #run: dotnet test ./ThrowGuard.sln -c Release --no-build --verbosity normal
